import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/features/app-sidebar";
import { Header } from "@/components/features/header";
import AudioPlayer from "@/components/features/audio-player";
import { LayoutWithPlayer } from "@/components/features/layout-with-player";
import { AuthProvider } from "@/providers/auth-provider";
import { getServerSession } from "next-auth";
import prisma from "@/lib/prisma";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const playlists = await prisma.playlist.findMany({
    where: {
      userId: session?.user.id,
    },
    select: {
      id: true,
      title: true,
      imageId: true,
      user: {
        select: {
          image: true,
          id: true,
          name: true,
        },
      },
    },
  });

  return (
    <AuthProvider session={session}>
      <SidebarProvider>
        <AppSidebar playlists={playlists} />
        <div className="flex flex-col min-w-0 flex-1">
          <Header />
          <LayoutWithPlayer>
            <main className="flex-1 p-12 space-y-8 mt-15">{children}</main>
          </LayoutWithPlayer>
        </div>
        <AudioPlayer />
      </SidebarProvider>
    </AuthProvider>
  );
}
