/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artists/all-static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findAllStatic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findAll"];
        put?: never;
        post: operations["ArtistsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ArtistsController_update"];
        trace?: never;
    };
    "/artists/profile/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ArtistsController_follow"];
        delete: operations["ArtistsController_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/image/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_findOneByEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findAll"];
        put?: never;
        post: operations["AlbumsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GenresController_findAll"];
        put?: never;
        post: operations["GenresController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/genres/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GenresController_findOne"];
        put?: never;
        post?: never;
        delete: operations["GenresController_remove"];
        options?: never;
        head?: never;
        patch: operations["GenresController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArtistSlugResponse: {
            slug: string;
        };
        PageMetaDto: {
            page: number;
            take: number;
            itemCount: number;
            pageCount: number;
            hasPreviousPage: boolean;
            hasNextPage: boolean;
        };
        PageDto: {
            data: unknown[][];
            meta: components["schemas"]["PageMetaDto"];
        };
        SongEntity: {
            id: string;
            title: string;
            audioId: string;
            duration: number;
            songNumber: number;
            lyrics: string | null;
            isExplicit: boolean;
            playCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            albumId: string;
        };
        ArtistEntity: {
            id: string;
            name: string;
            slug: string;
            avatarId: string | null;
            bannerId: string | null;
            avatarColor: string | null;
            bannerColor: string | null;
            bio: string | null;
            followersCount: number;
            songs?: components["schemas"]["SongEntity"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            avatarUrl: string | null;
            bannerUrl: string | null;
        };
        CreateArtistDto: {
            name: string;
            bio?: string | null;
            avatarId?: string | null;
            avatarColor?: string | null;
            bannerId?: string | null;
            bannerColor?: string | null;
        };
        UpdateArtistDto: {
            name?: string;
            bio?: string | null;
            avatarId?: string | null;
            avatarColor?: string | null;
            bannerId?: string | null;
            bannerColor?: string | null;
        };
        InfoDto: {
            id: string;
            name: string;
            slug: string;
            avatarId: string | null;
            bannerId: string | null;
            avatarColor: string | null;
            bannerColor: string | null;
            bio: string | null;
            followersCount: number;
        };
        PopularSongDto: {
            id: string;
            title: string;
            audioId: string;
            duration: number;
            songNumber: number;
            isExplicit: boolean;
            playCount: number;
        };
        AlbumArtistDto: {
            id: string;
            name: string;
        };
        DiscographyAlbumDto: {
            id: string;
            title: string;
            thumbnailId: string | null;
            /** @enum {string} */
            type: "SINGLE" | "EP" | "ALBUM";
            /** Format: date-time */
            releaseDate: string;
            artist: components["schemas"]["AlbumArtistDto"];
        };
        DiscographyDto: {
            albums: components["schemas"]["DiscographyAlbumDto"][];
            singlesAndEps: components["schemas"]["DiscographyAlbumDto"][];
        };
        ArtistProfileResponse: {
            info: components["schemas"]["InfoDto"];
            popularSongs: components["schemas"]["PopularSongDto"][];
            discography: components["schemas"]["DiscographyDto"];
        };
        UploadImageResponse: {
            publicId: string;
            dominantColor: string | null;
        };
        /** @enum {string} */
        UserRole: "USER" | "ADMIN";
        UserEntity: {
            id: string;
            email: string;
            name: string;
            image: string | null;
            /** @example USER */
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
        };
        UserResponseDto: {
            id: string;
            email: string;
            name: string;
            image: string | null;
            /** @example USER */
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterResponseDto: {
            access_token: string;
            user: components["schemas"]["UserResponseDto"];
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            access_token: string;
            user: components["schemas"]["UserResponseDto"];
        };
        CreateAlbumDto: {
            /** @example Midnight Memories */
            title: string;
            /** @example cloudinary_id_123 */
            thumbnailId?: string;
            /**
             * @default SINGLE
             * @enum {string}
             */
            type: "SINGLE" | "EP" | "ALBUM";
            /** @example 2023-10-27T00:00:00.000Z */
            releaseDate?: string;
            /**
             * Format: uuid
             * @description Artist ID
             */
            artistId: string;
        };
        AlbumEntity: {
            id: string;
            title: string;
            slug: string;
            thumbnailId: string | null;
            thumbnailColor: string | null;
            /** @enum {string} */
            type: "SINGLE" | "EP" | "ALBUM";
            /** Format: date-time */
            releaseDate: string;
            totalSongs: number;
            duration: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            artist?: components["schemas"]["ArtistEntity"];
            songs?: components["schemas"]["SongEntity"];
            genreList: components["schemas"]["GenreEntity"][];
            likesCount?: number;
            isLiked?: boolean;
            artistId: string;
            likedBy: string[];
            genres?: Record<string, never>[];
        };
        GenreEntity: {
            id: string;
            name: string;
            slug: string;
            songList: components["schemas"]["SongEntity"][];
            albumList: components["schemas"]["AlbumEntity"][];
            artistList: components["schemas"]["ArtistEntity"][];
            songs?: Record<string, never>[];
            albums?: Record<string, never>[];
            artists?: Record<string, never>[];
        };
        AlbumSlug: {
            slug: string;
        };
        AlbumItemResponse: {
            id: string;
            slug: string;
            thumbnailId: string | null;
            /** Format: date-time */
            releaseDate: string;
            artist?: components["schemas"]["ArtistEntity"];
        };
        AlbumDetailResponse: {
            id: string;
            title: string;
            slug: string;
            thumbnailId: string | null;
            thumbnailColor: string | null;
            /** @enum {string} */
            type: "SINGLE" | "EP" | "ALBUM";
            /** Format: date-time */
            releaseDate: string;
            totalSongs: number;
            duration: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            artist?: components["schemas"]["ArtistEntity"];
            songs?: components["schemas"]["SongEntity"];
            genreList: components["schemas"]["GenreEntity"][];
            likesCount?: number;
            isLiked?: boolean;
            artistId: string;
            likedBy: string[];
            genres?: Record<string, never>[];
        };
        CreateGenreDto: {
            name: string;
        };
        UpdateGenreDto: {
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ArtistsController_findAllStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all static artists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistSlugResponse"][];
                };
            };
        };
    };
    ArtistsController_findAll: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully received model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["ArtistEntity"][];
                    };
                };
            };
        };
    };
    ArtistsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtistDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"][];
                };
            };
        };
    };
    ArtistsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get basic artist info by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"];
                };
            };
        };
    };
    ArtistsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArtistDto"];
            };
        };
        responses: {
            /** @description Updated successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"][];
                };
            };
        };
    };
    ArtistsController_findProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get artist profile by id or slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistProfileResponse"];
                };
            };
        };
    };
    ArtistsController_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ArtistsController_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_uploadImage: {
        parameters: {
            query: {
                folder: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponse"];
                };
            };
        };
    };
    UserController_findOneByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AlbumsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get album list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumItemResponse"][];
                };
            };
        };
    };
    AlbumsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlbumDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumEntity"];
                };
            };
        };
    };
    AlbumsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get album details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetailResponse"];
                };
            };
        };
    };
    GenresController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    GenresController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenreDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreEntity"][];
                };
            };
        };
    };
    GenresController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    GenresController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    GenresController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGenreDto"];
            };
        };
        responses: {
            /** @description Updated successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreEntity"][];
                };
            };
        };
    };
}
