/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artists/all-static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findAllStatic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of artists with pagination and search */
        get: operations["ArtistsController_findAll"];
        put?: never;
        post: operations["ArtistsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ArtistsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ArtistsController_update"];
        trace?: never;
    };
    "/artists/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{identifier}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArtistsController_findOneDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ArtistsController_follow"];
        delete: operations["ArtistsController_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/image/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_getAudioUploadSignature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_findOneByEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findAll"];
        put?: never;
        post: operations["AlbumsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/all-static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findAllStatic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{identifier}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlbumsController_findOneDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AlbumsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AlbumsController_update"];
        trace?: never;
    };
    "/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GenresController_findAll"];
        put?: never;
        post: operations["GenresController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/genres/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GenresController_findOne"];
        put?: never;
        post?: never;
        delete: operations["GenresController_remove"];
        options?: never;
        head?: never;
        patch: operations["GenresController_update"];
        trace?: never;
    };
    "/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SongsController_findAll"];
        put?: never;
        post: operations["SongsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SongsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["SongsController_remove"];
        options?: never;
        head?: never;
        patch: operations["SongsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PageOptionsDto: {
            /**
             * @description Order by time
             * @enum {string}
             */
            order?: "asc" | "desc";
            /** @description Page number */
            page?: number;
            /** @description Items per page */
            take?: number;
            /** @description Search keyword */
            q?: string;
        };
        PageMetaDto: {
            page: number;
            take: number;
            itemCount: number;
            pageCount: number;
            hasPreviousPage: boolean;
            hasNextPage: boolean;
        };
        PageDto: {
            data: unknown[][];
            meta: components["schemas"]["PageMetaDto"];
        };
        /** @enum {string} */
        AlbumType: "SINGLE" | "EP" | "ALBUM";
        SongArtistEntity: {
            /** @enum {string} */
            type: "MAIN" | "FEATURED";
            order: number;
            artist?: components["schemas"]["ArtistEntity"];
            song?: components["schemas"]["SongEntity"];
            songId: string;
            artistId: string;
            id: string;
        };
        ArtistEntity: {
            id: string;
            name: string;
            slug: string;
            avatarId: string | null;
            bannerId: string | null;
            avatarColor: string | null;
            bannerColor: string | null;
            bio: string | null;
            followersCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            avatarUrl: string | null;
            bannerUrl: string | null;
            genres?: components["schemas"]["ArtistGenreEntity"][];
            songs?: components["schemas"]["SongArtistEntity"][];
            albums?: components["schemas"]["AlbumEntity"][];
        };
        AlbumGenreEntity: {
            genre?: components["schemas"]["GenreEntity"];
            album?: components["schemas"]["AlbumEntity"];
            albumId: string;
            genreId: string;
        };
        AlbumEntity: {
            id: string;
            title: string;
            slug: string;
            thumbnailId: string | null;
            thumbnailColor: string | null;
            /** @example ALBUM */
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate: string;
            totalDuration: number;
            songsCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            artist?: components["schemas"]["ArtistEntity"];
            songs?: components["schemas"]["SongEntity"][];
            genres?: components["schemas"]["AlbumGenreEntity"][];
            thumbnailUrl: string | null;
            artistId: string;
            likedBy: string[];
        };
        SongCreditEntity: {
            /** @enum {string} */
            role: "PRODUCER" | "COMPOSER" | "WRITER" | "ARRANGER" | "ENGINEER" | "BACKGROUND_VOCAL";
            name: string | null;
            artist: components["schemas"]["ArtistEntity"] | null;
            songId: string;
            artistId: string | null;
        };
        SongGenreEntity: {
            genre: components["schemas"]["GenreEntity"];
            songId: string;
            genreId: string;
            id: string;
        };
        SongEntity: {
            id: string;
            title: string;
            slug: string;
            audioUrl: Record<string, never>;
            duration: number;
            order: number;
            lyrics: string | null;
            isExplicit: boolean;
            playCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            albumId: string;
            album?: components["schemas"]["AlbumEntity"];
            artists?: components["schemas"]["SongArtistEntity"][];
            credits?: components["schemas"]["SongCreditEntity"][];
            genres?: components["schemas"]["SongGenreEntity"][];
            audioId: string;
        };
        GenreEntity: {
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            songList: components["schemas"]["SongEntity"][];
            albumList: components["schemas"]["AlbumEntity"][];
            artistList: components["schemas"]["ArtistEntity"][];
            songs?: Record<string, never>[];
            albums?: Record<string, never>[];
            artists?: Record<string, never>[];
        };
        ArtistGenreEntity: {
            genre?: components["schemas"]["GenreEntity"];
            artist?: components["schemas"]["ArtistEntity"];
            artistId: string;
            genreId: string;
        };
        ArtistSlugResponse: {
            slug: string;
        };
        CreateArtistDto: {
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds: string[];
            name: string;
            bio?: string | null;
            avatarId?: string | null;
            avatarColor?: string | null;
            bannerId?: string | null;
            bannerColor?: string | null;
        };
        UpdateArtistDto: {
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds?: string[];
            name?: string;
            bio?: string | null;
            avatarId?: string | null;
            avatarColor?: string | null;
            bannerId?: string | null;
            bannerColor?: string | null;
        };
        InfoDto: {
            id: string;
            name: string;
            slug: string;
            avatarId: string | null;
            bannerId: string | null;
            avatarColor: string | null;
            bannerColor: string | null;
            bio: string | null;
            followersCount: number;
        };
        PopularSongDto: {
            id: string;
            title: string;
            slug: string;
            duration: number;
            order: number;
            isExplicit: boolean;
            playCount: number;
            audioId: string;
        };
        AlbumArtistDto: {
            id: string;
            name: string;
        };
        DiscographyAlbumDto: {
            id: string;
            title: string;
            thumbnailId: string | null;
            /** @example ALBUM */
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate: string;
            artist: components["schemas"]["AlbumArtistDto"];
        };
        DiscographyDto: {
            albums: components["schemas"]["DiscographyAlbumDto"][];
            singlesAndEps: components["schemas"]["DiscographyAlbumDto"][];
        };
        ArtistDetailsResponse: {
            info: components["schemas"]["InfoDto"];
            popularSongs: components["schemas"]["PopularSongDto"][];
            discography: components["schemas"]["DiscographyDto"];
        };
        UploadImageResponse: {
            publicId: string;
            dominantColor: string | null;
        };
        UploadSignatureResponse: {
            publicId: string;
            timestamp: number;
            signature: string;
            folder: string;
            apiKey: string;
            cloudName: string;
            fetchColors: boolean;
        };
        /** @enum {string} */
        UserRole: "USER" | "ADMIN";
        UserEntity: {
            id: string;
            email: string;
            name: string;
            image: string | null;
            /** @example USER */
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
        };
        UserResponseDto: {
            id: string;
            email: string;
            name: string;
            image: string | null;
            /** @example USER */
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterResponseDto: {
            access_token: string;
            user: components["schemas"]["UserResponseDto"];
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            access_token: string;
            user: components["schemas"]["UserResponseDto"];
        };
        CreateAlbumDto: {
            /** @example Midnight Memories */
            title: string;
            /** @example cloudinary_id_123 */
            thumbnailId?: string | null;
            /**
             * @default SINGLE
             * @enum {string}
             */
            type: "SINGLE" | "EP" | "ALBUM";
            /** @example 2023-10-27T00:00:00.000Z */
            releaseDate?: string;
            /**
             * Format: uuid
             * @description Artist ID
             */
            artistId: string;
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds: string[];
            thumbnailColor?: string | null;
        };
        AlbumSlug: {
            slug: string;
        };
        AlbumDetailsResponse: {
            id: string;
            title: string;
            slug: string;
            thumbnailId: string | null;
            thumbnailColor: string | null;
            /** @example ALBUM */
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate: string;
            totalDuration: number;
            songsCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            artist?: components["schemas"]["ArtistEntity"];
            songs?: components["schemas"]["SongEntity"][];
            genres?: components["schemas"]["AlbumGenreEntity"][];
            thumbnailUrl: string | null;
            artistId: string;
            likedBy: string[];
        };
        UpdateAlbumDto: {
            /** @example Midnight Memories */
            title?: string;
            /** @example cloudinary_id_123 */
            thumbnailId?: string | null;
            /**
             * @default SINGLE
             * @enum {string}
             */
            type: "SINGLE" | "EP" | "ALBUM";
            /** @example 2023-10-27T00:00:00.000Z */
            releaseDate?: string;
            /**
             * Format: uuid
             * @description Artist ID
             */
            artistId?: string;
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds?: string[];
            thumbnailColor?: string | null;
        };
        CreateGenreDto: {
            name: string;
        };
        UpdateGenreDto: {
            name?: string;
        };
        SongArtistDto: {
            artistId: string;
            /** @enum {string} */
            type: "MAIN" | "FEATURED";
        };
        SongCreditDto: {
            /** @enum {string} */
            role: "PRODUCER" | "COMPOSER" | "WRITER" | "ARRANGER" | "ENGINEER" | "BACKGROUND_VOCAL";
            artistId?: string;
            name?: string;
        };
        CreateSongDto: {
            /** @description Song title */
            title: string;
            /** @description Cloudinary Audio Public ID */
            audioId: string;
            /** @description Duration in seconds */
            duration: number;
            /** @description Song lyrics */
            lyrics?: string | null;
            /** @default false */
            isExplicit: boolean;
            /**
             * Format: uuid
             * @description Album ID
             */
            albumId: string;
            artists: components["schemas"]["SongArtistDto"][];
            credits: components["schemas"]["SongCreditDto"][];
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds: string[];
        };
        UpdateSongDto: {
            /** @description Song title */
            title?: string;
            /** @description Cloudinary Audio Public ID */
            audioId?: string;
            /** @description Duration in seconds */
            duration?: number;
            /** @description Song lyrics */
            lyrics?: string | null;
            /** @default false */
            isExplicit: boolean;
            /**
             * Format: uuid
             * @description Album ID
             */
            albumId?: string;
            artists?: components["schemas"]["SongArtistDto"][];
            credits?: components["schemas"]["SongCreditDto"][];
            /**
             * @description List of Genre IDs
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            genreIds?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ArtistsController_findAllStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all static artists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistSlugResponse"][];
                };
            };
        };
    };
    ArtistsController_findAll: {
        parameters: {
            query?: {
                /** @description Order by time */
                order?: "asc" | "desc";
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                take?: number;
                /** @description Search keyword */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully received model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["ArtistEntity"][];
                    };
                };
            };
        };
    };
    ArtistsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtistDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"][];
                };
            };
        };
    };
    ArtistsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"][];
                };
            };
        };
    };
    ArtistsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArtistDto"];
            };
        };
        responses: {
            /** @description Artist updated successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"][];
                };
            };
        };
    };
    ArtistsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get basic artist info by identifier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistEntity"];
                };
            };
        };
    };
    ArtistsController_findOneDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get artist profile by id or slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetailsResponse"];
                };
            };
        };
    };
    ArtistsController_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ArtistsController_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_uploadImage: {
        parameters: {
            query: {
                folder: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponse"];
                };
            };
        };
    };
    MediaController_getAudioUploadSignature: {
        parameters: {
            query: {
                filename: string;
                folder: string;
                resourceType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignatureResponse"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignatureResponse"];
                };
            };
        };
    };
    UserController_findOneByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AlbumsController_findAll: {
        parameters: {
            query?: {
                /** @description Order by time */
                order?: "asc" | "desc";
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                take?: number;
                /** @description Search keyword */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully received model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["AlbumEntity"][];
                    };
                };
            };
        };
    };
    AlbumsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlbumDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumEntity"];
                };
            };
        };
    };
    AlbumsController_findAllStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get full static albums */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumSlug"][];
                };
            };
        };
    };
    AlbumsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get album by identifier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumEntity"];
                };
            };
        };
    };
    AlbumsController_findOneDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get album detail by identifier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetailsResponse"];
                };
            };
        };
    };
    AlbumsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album removed successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumEntity"][];
                };
            };
        };
    };
    AlbumsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlbumDto"];
            };
        };
        responses: {
            /** @description Album updated successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumEntity"][];
                };
            };
        };
    };
    GenresController_findAll: {
        parameters: {
            query?: {
                /** @description Order by time */
                order?: "asc" | "desc";
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                take?: number;
                /** @description Search keyword */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully received model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDto"] & {
                        data?: components["schemas"]["GenreEntity"][];
                    };
                };
            };
        };
    };
    GenresController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenreDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreEntity"][];
                };
            };
        };
    };
    GenresController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get basic genre info by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreEntity"];
                };
            };
        };
    };
    GenresController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    GenresController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGenreDto"];
            };
        };
        responses: {
            /** @description Updated successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreEntity"][];
                };
            };
        };
    };
    SongsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    SongsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSongDto"];
            };
        };
        responses: {
            /** @description Created successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongEntity"];
                };
            };
        };
    };
    SongsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    SongsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    SongsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSongDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
