import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/features/app-sidebar";
import { Header } from "@/components/features/header";
import AudioPlayer from "@/components/features/audio-player";
import { LayoutWithPlayer } from "@/components/features/layout-with-player";
import { ThemeProvider } from "@/providers/theme-provider";

const lexendSans = Lexend({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${lexendSans.className} scroll-smooth overflow-x-hidden overflow-y-scroll overscroll-none`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body className="antialiased min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-col min-w-0 flex-1">
              <Header />
              <LayoutWithPlayer>
                <main className="flex-1 p-12 space-y-8 mt-15">{children}</main>
              </LayoutWithPlayer>
            </div>
            <AudioPlayer />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
