import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/features/app-sidebar";
import { Header } from "@/components/features/header";
import AudioPlayer from "@/components/features/audio-player";
import { AuthProvider } from "@/providers/auth-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { PlayerOffsetSetter } from "@/components/features/player-offset-setter";
import { ScrollArea } from "@/components/ui/scroll-area";
import RightPanel from "@/components/features/right-panel";
import ReactQueryProvider from "@/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";

const lexendSans = Lexend({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${lexendSans.className} h-dvh overflow-hidden overscroll-none`}
      suppressHydrationWarning
    >
      <body className="antialiased h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <AuthProvider session={session}>
              <SidebarProvider
                className="h-full"
                style={
                  {
                    "--header-height": "calc(var(--spacing) * 15)",
                  } as React.CSSProperties
                }
              >
                <AppSidebar />
                <SidebarInset
                  className="h-full transition-[width]"
                  style={{
                    paddingBottom:
                      "calc(env(safe-area-inset-bottom) + var(--player-offset, 0px))",
                  }}
                >
                  <ScrollArea viewportId="app-scroll" className="h-full">
                    <Header />
                    <div className="flex flex-col flex-1 p-6 md:p-8 lg:p-10 xl:p-12">
                      <div className="@container/main flex flex-1 flex-col gap-8">
                        <PlayerOffsetSetter />
                        {children}
                      </div>
                    </div>
                  </ScrollArea>
                </SidebarInset>
                <RightPanel />
                <AudioPlayer />
                <Toaster />
              </SidebarProvider>
            </AuthProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
